const questionStore = [
    { question: "Solve the equation: 2x + 8 = 16", subject: "Mathematics", topic: "Algebra", difficulty: "Easy", marks: 5 },
    { question: "What is the capital of France?", subject: "Geography", topic: "Geography", difficulty: "Easy", marks: 5 },
    { question: "What type of waves are used in mobile communication?", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Expand the expression: (a + b)^2", subject: "Mathematics", topic: "Algebra", difficulty: "Easy", marks: 5 },
    { question: "Name the largest ocean on Earth", subject: "Geography", topic: "Geography", difficulty: "Easy", marks: 5 },
    { question: "Explain the concept of reflection in waves", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Factorize the expression: 3x^2 - 12", subject: "Mathematics", topic: "Algebra", difficulty: "Easy", marks: 5 },
    { question: "What is the capital of Japan?", subject: "Geography", topic: "Geography", difficulty: "Easy", marks: 5 },
    { question: "Define the term 'frequency' in waves", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Simplify the expression: 5y + 2y - 3y", subject: "Mathematics", topic: "Algebra", difficulty: "Easy", marks: 5 },
    { question: "Solve the system of equations: x + y = 10, 2x - y = 5", subject: "Mathematics", topic: "Algebra", difficulty: "Medium", marks: 5 },
    { question: "Name the capital of Australia", subject: "Geography", topic: "Geography", difficulty: "Medium", marks: 5 },
    { question: "Discuss the phenomenon of interference in waves", subject: "Physics", topic: "Waves", difficulty: "Medium", marks: 5 },
    { question: "Factorize the quadratic expression: x^2 - 6x + 9", subject: "Mathematics", topic: "Algebra", difficulty: "Medium", marks: 5 },
    { question: "Identify the mountain range: Himalayas", subject: "Geography", topic: "Geography", difficulty: "Medium", marks: 5 },
    { question: "Explain the Doppler effect in waves", subject: "Physics", topic: "Waves", difficulty: "Medium", marks: 5 },
    { question: "Simplify the algebraic expression: 3a - (2a + 5)", subject: "Mathematics", topic: "Algebra", difficulty: "Medium", marks: 5 },
    { question: "Name the capital of Brazil", subject: "Geography", topic: "Geography", difficulty: "Medium", marks: 5 },
    { question: "Define the term 'amplitude' in waves", subject: "Physics", topic: "Waves", difficulty: "Medium", marks: 5 },
    { question: "Solve the inequality: 2x + 3 > 7", subject: "Mathematics", topic: "Algebra", difficulty: "Medium", marks: 5 },
    { question: "Solve the system of equations: 3x - y = 6, 2x + 2y = 8", subject: "Mathematics", topic: "Algebra", difficulty: "Hard", marks: 5 },
    { question: "Name the capital of Mongolia", subject: "Geography", topic: "Geography", difficulty: "Hard", marks: 5 },
    { question: "Explain the concept of diffraction in waves", subject: "Physics", topic: "Waves", difficulty: "Hard", marks: 5 },
    { question: "Factorize the quadratic expression: 2x^2 - 5x - 3", subject: "Mathematics", topic: "Algebra", difficulty: "Hard", marks: 5 },
    { question: "Identify the desert: Sahara", subject: "Geography", topic: "Geography", difficulty: "Hard", marks: 5 },
    { question: "Discuss the principles of wave-particle duality", subject: "Physics", topic: "Waves", difficulty: "Hard", marks: 5 },
    { question: "Simplify the expression: (4a^2 - 9) / (2a + 3)", subject: "Mathematics", topic: "Algebra", difficulty: "Hard", marks: 5 },
    { question: "Name the capital of South Africa", subject: "Geography", topic: "Geography", difficulty: "Hard", marks: 5 },
    { question: "Define the term 'refraction' in waves", subject: "Physics", topic: "Waves", difficulty: "Hard", marks: 5 },
    { question: "Solve the logarithmic equation: log(base 2)(x) = 3", subject: "Mathematics", topic: "Algebra", difficulty: "Hard", marks: 5 },
];

module.exports = questionStore;