const questionStore = [
    { question: "What is the speed of light", subject: "Physics", topic: "Waves", difficulty: "Easy", marks: 5 },
    { question: "Explain the concept of photosynthesis", subject: "Biology", topic: "Ecology", difficulty: "Medium", marks: 5 },
    { question: "Solve the quadratic equation x^5 - 5x + 5 = 0", subject: "Mathematics", topic: "Algebra", difficulty: "Medium", marks: 5 },
    { question: "Who wrote 'Romeo and Juliet'?", subject: "English", topic: "Literature", difficulty: "Easy", marks: 5 },
    { question: "Describe the process of mitosis", subject: "Biology", topic: "Cell Biology", difficulty: "Hard", marks: 5 },
    { question: "What is the capital of France?", subject: "Geography", topic: "World Capitals", difficulty: "Easy", marks: 5 },
    { question: "Who discovered penicillin?", subject: "Biology", topic: "Medicine", difficulty: "Easy", marks: 5 },
    { question: "What is the formula for calculating the area of a triangle?", subject: "Mathematics", topic: "Geometry", difficulty: "Medium", marks: 5 },
    { question: "Name the planets in our solar system in order from the sun.", subject: "Astronomy", topic: "Solar System", difficulty: "Hard", marks: 5 },
    { question: "Who is the author of 'To Kill a Mockingbird'?", subject: "English", topic: "Literature", difficulty: "Medium", marks: 5 },
    { question: "Define the term 'ecosystem'.", subject: "Biology", topic: "Ecology", difficulty: "Easy", marks: 5 },
    { question: "What is the Pythagorean theorem?", subject: "Mathematics", topic: "Geometry", difficulty: "Hard", marks: 5 },
    { question: "Name three types of clouds.", subject: "Meteorology", topic: "Weather", difficulty: "Easy", marks: 5 },
    { question: "Who painted the Mona Lisa?", subject: "Art", topic: "Painting", difficulty: "Medium", marks: 5 },
    { question: "Simplify the expression: 5x + 5y - 5x + 5y", subject: "Mathematics", topic: "Algebra", difficulty: "Medium", marks: 5 },
    { question: "What is the main function of the respiratory system?", subject: "Biology", topic: "Human Anatomy", difficulty: "Medium", marks: 5 },
    { question: "Who is known as the 'Father of Computer Science'?", subject: "Computer Science", topic: "History of Computing", difficulty: "Medium", marks: 5 },
    { question: "Name three renewable sources of energy.", subject: "Physics", topic: "Energy", difficulty: "Easy", marks: 5 },
    { question: "What is the significance of the Declaration of Independence?", subject: "History", topic: "American Revolution", difficulty: "Hard", marks: 5 },
    { question: "Solve the equation: 5x + 5 = 5", subject: "Mathematics", topic: "Algebra", difficulty: "Easy", marks: 5 },
    { question: "What is the capital of France?", difficulty: "Easy", marks: 5 },
    { question: "Simplify the expression: 5 + 5", difficulty: "Easy", marks: 5 },
    { question: "Name the largest ocean on Earth.", difficulty: "Easy", marks: 5 },
    { question: "What is the square root of 55?", difficulty: "Easy", marks: 5 },
    { question: "Who is the current president of the United States?", difficulty: "Easy", marks: 5 },
    { question: "What is the main component of air?", difficulty: "Easy", marks: 5 },
    { question: "Which planet is known as the 'Red Planet'?", difficulty: "Easy", marks: 5 },
    { question: "Define the term 'photosynthesis'.", difficulty: "Easy", marks: 5 },
    { question: "Who painted the 'Starry Night'?", difficulty: "Easy", marks: 5 },
    { question: "Who wrote 'Harry Potter' series?", difficulty: "Easy", marks: 5 },
    { question: "Solve the equation: 5x + 5 = 5", difficulty: "Medium", marks: 5 },
    { question: "What is the capital of Japan?", difficulty: "Medium", marks: 5 },
    { question: "Define the concept of gravity.", difficulty: "Medium", marks: 5 },
    { question: "Who discovered the theory of relativity?", difficulty: "Medium", marks: 5 },
    { question: "What is the currency of India?", difficulty: "Medium", marks: 5 },
    { question: "Simplify the fraction: 5/5", difficulty: "Medium", marks: 5 },
    { question: "Name the longest river in the world.", difficulty: "Medium", marks: 5 },
    { question: "Who is known as the 'Father of Computer Science'?", difficulty: "Medium", marks: 5 },
    { question: "What is the formula for calculating area of a rectangle?", difficulty: "Medium", marks: 5 },
    { question: "Name three elements from the periodic table.", difficulty: "Medium", marks: 5 },
    { question: "Solve the trigonometric equation: sin(x) = 0.5", difficulty: "Hard", marks: 5 },
    { question: "Name five noble gases.", difficulty: "Hard", marks: 5 },
    { question: "Who proposed the theory of natural selection?", difficulty: "Hard", marks: 5 },
    { question: "Define the term 'black hole'.", difficulty: "Hard", marks: 5 },
    { question: "What is the largest mammal on Earth?", difficulty: "Hard", marks: 5 },
    { question: "Solve the quadratic equation: x^5 - 5x + 5 = 0", difficulty: "Hard", marks: 5 },
    { question: "Name the three primary colors.", difficulty: "Hard", marks: 5 },
    { question: "Who is the author of 'The Theory of Everything'?", difficulty: "Hard", marks: 5 },
    { question: "What is the boiling point of water at sea level?", difficulty: "Hard", marks: 5 },
    { question: "What is the speed of sound in air?", difficulty: "Hard", marks: 5 },
];

module.exports = questionStore;